### ISSUE TITLE
Experiment with GC options?

### ISSUE THREAD

**Issue by Boarders** [0xd34df00d/hwc#1]
This was a fantastic blog post and I look forward to where this project goes! I wonder if you also have experimented with trying out different GC options to see if this makes any noticeable difference? (I can't imagine it will but nevertheless thought it might be worth a quick experiment). For instance you can change the allocation area (which by default is 1MB) to 1GB as follows:
```
./hwc -A1G
```

**Comment by 0xd34df00d** [comment]
Thanks for the feedback, I'm glad you've found this interesting!

GC shouldn't affect the run time here (at least right now), since we're `mmap`ing the input file (so it's outside of what's Haskell GC is responsible for), and the processing happens in a tight loop in `O(1)` of memory. For instance, `+RTS -sstderr` shows
```
          80,552 bytes allocated in the heap
          32,832 bytes copied during GC
          57,944 bytes maximum residency (2 sample(s))
          28,072 bytes maximum slop
               0 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         2 colls,     0 par    0.000s   0.000s     0.0001s    0.0002s
``` 

And, practically, changing `-A` setting does not affect the run time in a statistically significant way.

**Comment by Boarders** [comment]
Ah yes, that is embarrassing! I forgot that bytestrings are not on the (GC managed) heap. I actually got the idea for this sort of experimentation from this benchmark: https://github.com/AndrasKovacs/normalization-bench which suggests that `-A` definitely can have a big import for certain applications.
